FROM node:20-alpine AS runner

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy monorepo config files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps
COPY services ./services

# Install dependencies and build monorepo packages
RUN pnpm install --frozen-lockfile
RUN pnpm --recursive --workspace-concurrency=4 run build

ENV NODE_ENV=production

CMD ["node", "apps/render-worker/dist/index.js"]
