/**
 * Historical Location Dictionary & Same-As Mappings (SSOT)
 */
import type { HistoricalLocationMapping } from '../interfaces.js';
import type { HistoricalEntityInfo } from './types.js';

export const HISTORICAL_LOCATION_MAPPINGS: HistoricalLocationMapping[] = [
  {
    historicalName: 'Thăng Long',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Nhà Lý / Nhà Trần / Nhà Lê',
    timeRange: { start: 1010, end: 1788 },
  },
  {
    historicalName: 'Đông Quan',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Thuộc Minh',
    timeRange: { start: 1407, end: 1427 },
  },
  {
    historicalName: 'Đông Kinh',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Nhà Lê Sơ',
    timeRange: { start: 1430, end: 1788 },
  },
  {
    historicalName: 'Tống Bình',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Thuộc Tùy - Đường',
    timeRange: { start: 602, end: 905 },
  },
  {
    historicalName: 'Đại La',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Thuộc Đường',
    timeRange: { start: 866, end: 1010 },
  },
  {
    historicalName: 'Phú Xuân',
    canonicalModernName: 'Huế',
    dynasty: 'Chúa Nguyễn / Nhà Tây Sơn / Nhà Nguyễn',
    timeRange: { start: 1687, end: 1945 },
  },
  {
    historicalName: 'Thuận Hóa',
    canonicalModernName: 'Huế',
    dynasty: 'Nhà Hậu Lê / Chúa Nguyễn',
    timeRange: { start: 1306, end: 1687 },
  },
  {
    historicalName: 'Sài Gòn',
    canonicalModernName: 'Thành phố Hồ Chí Minh',
    dynasty: 'Nhà Nguyễn / Pháp thuộc / VNCH',
    timeRange: { start: 1698, end: 1975 },
  },
  {
    historicalName: 'Gia Định',
    canonicalModernName: 'Thành phố Hồ Chí Minh',
    dynasty: 'Nhà Nguyễn',
    timeRange: { start: 1698, end: 1862 },
  },
  {
    historicalName: 'Hoa Lư',
    canonicalModernName: 'Ninh Bình',
    dynasty: 'Nhà Đinh / Nhà Tiền Lê',
    timeRange: { start: 968, end: 1010 },
  },
  {
    historicalName: 'Cố đô Hoa Lư',
    canonicalModernName: 'Ninh Bình',
    dynasty: 'Nhà Đinh / Nhà Tiền Lê',
    timeRange: { start: 968, end: 1010 },
  },
  {
    historicalName: 'Đông Bộ Đầu',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Nhà Trần',
    timeRange: { start: 1225, end: 1400 },
  },
  {
    historicalName: 'Bắc Thành',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Nhà Nguyễn',
    timeRange: { start: 1802, end: 1831 },
  },
  {
    historicalName: 'Gia Định Thành',
    canonicalModernName: 'Thành phố Hồ Chí Minh',
    dynasty: 'Nhà Nguyễn',
    timeRange: { start: 1802, end: 1832 },
  },
  {
    historicalName: 'phủ Thừa Thiên',
    canonicalModernName: 'Huế',
    dynasty: 'Nhà Nguyễn',
    timeRange: { start: 1802, end: 1945 },
  },
  {
    historicalName: 'thành Quy Nhơn',
    canonicalModernName: 'Bình Định',
    dynasty: 'Tây Sơn / Nhà Nguyễn',
    timeRange: { start: 1778, end: 1802 },
  },
  {
    historicalName: 'Quy Nhơn',
    canonicalModernName: 'Bình Định',
    dynasty: 'Tây Sơn / Nhà Nguyễn',
    timeRange: { start: 1778, end: 1802 },
  },
  {
    historicalName: 'Tây Đô',
    canonicalModernName: 'Thanh Hóa',
    dynasty: 'Nhà Hồ',
    timeRange: { start: 1397, end: 1407 },
  },
  {
    historicalName: 'Yên Kinh',
    canonicalModernName: 'Bắc Kinh',
    dynasty: 'Nhà Nguyên / Nhà Minh / Nhà Thanh',
    timeRange: { start: 1271, end: 1912 },
  },
  {
    historicalName: 'Hoan Châu',
    canonicalModernName: 'Nghệ An',
    dynasty: 'Bắc thuộc / Nhà Đinh / Tiền Lê',
    timeRange: { start: 602, end: 1010 },
  },
  {
    historicalName: 'Phú Điền',
    canonicalModernName: 'Thanh Hóa',
    dynasty: 'Bắc thuộc lần 2',
    timeRange: { start: 248, end: 248 },
  },
  {
    historicalName: 'Tây Đô',
    canonicalModernName: 'Cần Thơ',
    dynasty: 'Cận - Hiện đại',
    timeRange: { start: 1900, end: 2026 },
  },
  {
    historicalName: 'Phong Khê',
    canonicalModernName: 'Đông Anh',
    dynasty: 'Âu Lạc',
    timeRange: { start: -257, end: -179 },
  },
  {
    historicalName: 'Hà Tây',
    canonicalModernName: 'Hà Nội',
    dynasty: 'Hiện đại',
    timeRange: { start: 1965, end: 2008 },
  },
  {
    historicalName: 'Thủ Dầu Một',
    canonicalModernName: 'Bình Dương',
    dynasty: 'Cận - Hiện đại',
    timeRange: { start: 1860, end: 2026 },
  },
  {
    historicalName: 'Kinh thành Huế',
    canonicalModernName: 'Huế',
    dynasty: 'Nhà Nguyễn',
    timeRange: { start: 1802, end: 1945 },
  },
  {
    historicalName: 'núi Nưa',
    canonicalModernName: 'Nông Cống',
    dynasty: 'Bắc thuộc lần 2',
    timeRange: { start: 248, end: 248 },
  },
  {
    historicalName: 'Vụ Quang',
    canonicalModernName: 'Hà Tĩnh',
    dynasty: 'Cận đại',
    timeRange: { start: 1885, end: 1896 },
  },
];

/**
 * Built-in Historical Location Dictionary with Canonical Entity IDs and Aliases
 */
export const HISTORICAL_LOCATION_DICTIONARY: Record<string, HistoricalEntityInfo> = {
  'loc_ha_noi': {
    entityId: 'loc_ha_noi',
    canonicalName: 'Hà Nội',
    type: 'LOCATION',
    aliases: ['thành phố Hà Nội', 'Hà Thành', 'Bắc Thành'],
  },
  'loc_thang_long': {
    entityId: 'loc_thang_long',
    canonicalName: 'Thăng Long',
    type: 'LOCATION',
    aliases: ['kinh đô Thăng Long', 'hoàng thành Thăng Long', 'Đông Đô', 'Kinh Kỳ', 'Đại La', 'thành Đại La'],
  },
  'loc_dong_kinh': {
    entityId: 'loc_dong_kinh',
    canonicalName: 'Đông Kinh',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_dong_quan': {
    entityId: 'loc_dong_quan',
    canonicalName: 'Đông Quan',
    type: 'LOCATION',
    aliases: ['thành Đông Quan'],
  },
  'loc_tong_binh': {
    entityId: 'loc_tong_binh',
    canonicalName: 'phủ Tống Bình',
    type: 'LOCATION',
    aliases: ['Tống Bình'],
  },
  'loc_hoa_lu': {
    entityId: 'loc_hoa_lu',
    canonicalName: 'Hoa Lư',
    type: 'LOCATION',
    aliases: ['cố đô Hoa Lư', 'Cố đô Hoa Lư', 'kinh đô Hoa Lư'],
  },
  'loc_phu_xuan': {
    entityId: 'loc_phu_xuan',
    canonicalName: 'thành Phú Xuân',
    type: 'LOCATION',
    aliases: ['Phú Xuân', 'kinh thành Phú Xuân'],
  },
  'loc_sai_gon': {
    entityId: 'loc_sai_gon',
    canonicalName: 'Sài Gòn',
    type: 'LOCATION',
    aliases: ['Gia Định', 'Gia Định Thành'],
  },
  'loc_quy_nhon': {
    entityId: 'loc_quy_nhon',
    canonicalName: 'Quy Nhơn',
    type: 'LOCATION',
    aliases: ['thành Quy Nhơn', 'Thành Quy Nhơn'],
  },
  'loc_phong_chau': {
    entityId: 'loc_phong_chau',
    canonicalName: 'Phong Châu',
    type: 'LOCATION',
    aliases: ['kinh đô Phong Châu'],
  },
  'loc_hue': {
    entityId: 'loc_hue',
    canonicalName: 'Huế',
    type: 'LOCATION',
    aliases: ['thành phố Huế', 'Cố đô Huế'],
  },
  'loc_khiem_lang': {
    entityId: 'loc_khiem_lang',
    canonicalName: 'Khiêm Lăng',
    type: 'LOCATION',
    aliases: ['lăng Tự Đức', 'Khiêm Cung', 'Khiêm lăng'],
  },
  'loc_ho_chi_minh': {
    entityId: 'loc_ho_chi_minh',
    canonicalName: 'Thành phố Hồ Chí Minh',
    type: 'LOCATION',
    aliases: ['TP.HCM', 'TPHCM'],
  },
  'loc_binh_dinh': {
    entityId: 'loc_binh_dinh',
    canonicalName: 'Bình Định',
    type: 'LOCATION',
    aliases: ['tỉnh Bình Định'],
  },
  'loc_thanh_hoa': {
    entityId: 'loc_thanh_hoa',
    canonicalName: 'Thanh Hóa',
    type: 'LOCATION',
    aliases: ['tỉnh Thanh Hóa'],
  },
  'loc_nghe_an': {
    entityId: 'loc_nghe_an',
    canonicalName: 'Nghệ An',
    type: 'LOCATION',
    aliases: ['tỉnh Nghệ An'],
  },
  'loc_bac_kinh': {
    entityId: 'loc_bac_kinh',
    canonicalName: 'Bắc Kinh',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_ninh_binh': {
    entityId: 'loc_ninh_binh',
    canonicalName: 'Ninh Bình',
    type: 'LOCATION',
    aliases: ['tỉnh Ninh Bình'],
  },
  'loc_duong_lam': {
    entityId: 'loc_duong_lam',
    canonicalName: 'Đường Lâm',
    type: 'LOCATION',
    aliases: ['làng Đường Lâm', 'đất hai vua Đường Lâm'],
  },
  'loc_phu_dien': {
    entityId: 'loc_phu_dien',
    canonicalName: 'Phú Điền',
    type: 'LOCATION',
    aliases: ['Căn Cứ Phú Điền', 'căn cứ Phú Điền'],
  },
  'loc_tan_so': {
    entityId: 'loc_tan_so',
    canonicalName: 'Tân Sở',
    type: 'LOCATION',
    aliases: ['căn cứ Tân Sở', 'Căn cứ Tân Sở'],
  },
  'loc_dong_anh': {
    entityId: 'loc_dong_anh',
    canonicalName: 'Đông Anh',
    type: 'LOCATION',
    aliases: ['huyện Đông Anh', 'Đông Anh'],
  },
  'loc_ha_tay': {
    entityId: 'loc_ha_tay',
    canonicalName: 'Hà Tây',
    type: 'LOCATION',
    aliases: ['tỉnh Hà Tây', 'Hà Tây', 'xứ Đoài'],
  },
  'loc_phong_khe': {
    entityId: 'loc_phong_khe',
    canonicalName: 'Phong Khê',
    type: 'LOCATION',
    aliases: ['đất Phong Khê', 'kinh đô Phong Khê', 'Phong Khê'],
  },
  'loc_van_mieu': {
    entityId: 'loc_van_mieu',
    canonicalName: 'Văn Miếu',
    type: 'LOCATION',
    aliases: ['Văn Miếu Thăng Long', 'Văn Miếu - Quốc Tử Giám', 'Văn Miếu'],
  },
  'loc_the_mieu': {
    entityId: 'loc_the_mieu',
    canonicalName: 'Thế Miếu',
    type: 'LOCATION',
    aliases: ['sân Thế Miếu', 'Thế Miếu'],
  },
  'loc_thu_dau_mot': {
    entityId: 'loc_thu_dau_mot',
    canonicalName: 'Thủ Dầu Một',
    type: 'LOCATION',
    aliases: ['Thủ Dầu Một', 'đất Thủ Dầu Một', 'thành phố Thủ Dầu Một'],
  },
  'loc_binh_duong': {
    entityId: 'loc_binh_duong',
    canonicalName: 'Bình Dương',
    type: 'LOCATION',
    aliases: ['tỉnh Bình Dương', 'Bình Dương'],
  },
  'loc_kinh_thanh_hue': {
    entityId: 'loc_kinh_thanh_hue',
    canonicalName: 'Kinh thành Huế',
    type: 'LOCATION',
    aliases: ['Kinh thành Huế', 'kinh thành Huế', 'Hoàng thành Huế'],
  },
  'loc_nui_nua': {
    entityId: 'loc_nui_nua',
    canonicalName: 'núi Nưa',
    type: 'LOCATION',
    aliases: ['núi Nưa', 'Núi Nưa', 'ngàn Nưa'],
  },
  'loc_nong_cong': {
    entityId: 'loc_nong_cong',
    canonicalName: 'Nông Cống',
    type: 'LOCATION',
    aliases: ['huyện Nông Cống', 'Nông Cống'],
  },
  'loc_vu_quang': {
    entityId: 'loc_vu_quang',
    canonicalName: 'Vụ Quang',
    type: 'LOCATION',
    aliases: ['Vũ Quang', 'căn cứ Vụ Quang', 'Vụ Quang', 'căn cứ Vũ Quang'],
  },
  'loc_tan_hoa': {
    entityId: 'loc_tan_hoa',
    canonicalName: 'Tân Hòa',
    type: 'LOCATION',
    aliases: ['Tân Hòa', 'căn cứ Tân Hòa', 'đất Tân Hòa', 'đồn Tân Hòa'],
  },
  'loc_doi_a1': {
    entityId: 'loc_doi_a1',
    canonicalName: 'Đồi A1',
    type: 'LOCATION',
    aliases: ['Đồi A1', 'đồi A1', 'cứ điểm A1', 'cứ điểm đồi A1'],
  },
  'loc_ngoc_hoi': {
    entityId: 'loc_ngoc_hoi',
    canonicalName: 'Ngọc Hồi',
    type: 'LOCATION',
    aliases: ['đồn Ngọc Hồi', 'Ngọc Hồi'],
  },
  'loc_dong_da': {
    entityId: 'loc_dong_da',
    canonicalName: 'Đống Đa',
    type: 'LOCATION',
    aliases: ['gò Đống Đa', 'Đống Đa'],
  },
  'loc_duong_truong_son': {
    entityId: 'loc_duong_truong_son',
    canonicalName: 'đường Trường Sơn',
    type: 'LOCATION',
    aliases: ['Đường Trường Sơn', 'đường Trường Sơn', 'tuyến lửa Trường Sơn'],
  },
  'loc_duong_mon_ho_chi_minh': {
    entityId: 'loc_duong_mon_ho_chi_minh',
    canonicalName: 'đường mòn Hồ Chí Minh',
    type: 'LOCATION',
    aliases: ['Đường mòn Hồ Chí Minh', 'đường mòn Hồ Chí Minh', 'tuyến đường Hồ Chí Minh'],
  },
  'loc_giao_chau': {
    entityId: 'loc_giao_chau',
    canonicalName: 'Giao Châu',
    type: 'LOCATION',
    aliases: ['quận Giao Châu'],
  },
  'loc_hoan_chau': {
    entityId: 'loc_hoan_chau',
    canonicalName: 'Hoan Châu',
    type: 'LOCATION',
    aliases: ['châu Hoan'],
  },
  'loc_mo_cay': {
    entityId: 'loc_mo_cay',
    canonicalName: 'Mỏ Cày',
    type: 'LOCATION',
    aliases: ['huyện Mỏ Cày'],
  },
  'loc_dinh_doc_lap': {
    entityId: 'loc_dinh_doc_lap',
    canonicalName: 'Dinh Độc Lập',
    type: 'LOCATION',
    aliases: ['Hội trường Thống Nhất'],
  },
  'loc_thuy_dien_hoa_binh': {
    entityId: 'loc_thuy_dien_hoa_binh',
    canonicalName: 'Nhà máy Thủy điện Hòa Bình',
    type: 'LOCATION',
    aliases: ['Thủy điện Hòa Bình'],
  },
  'loc_song_da': {
    entityId: 'loc_song_da',
    canonicalName: 'sông Đà',
    type: 'LOCATION',
    aliases: ['Sông Đà'],
  },
  'loc_truong_sa': {
    entityId: 'loc_truong_sa',
    canonicalName: 'quần đảo Trường Sa',
    type: 'LOCATION',
    aliases: ['Trường Sa'],
  },
  'loc_quang_truong_ba_dinh': {
    entityId: 'loc_quang_truong_ba_dinh',
    canonicalName: 'Quảng trường Ba Đình',
    type: 'LOCATION',
    aliases: ['Ba Đình'],
  },
  'loc_viet_bac': {
    entityId: 'loc_viet_bac',
    canonicalName: 'Việt Bắc',
    type: 'LOCATION',
    aliases: ['chiến khu Việt Bắc'],
  },
  'loc_quang_chau': {
    entityId: 'loc_quang_chau',
    canonicalName: 'Quảng Châu',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_phu_thua_thien': {
    entityId: 'loc_phu_thua_thien',
    canonicalName: 'phủ Thừa Thiên',
    type: 'LOCATION',
    aliases: ['Thừa Thiên'],
  },
  'loc_nui_ban': {
    entityId: 'loc_nui_ban',
    canonicalName: 'núi Bân',
    type: 'LOCATION',
    aliases: ['Núi Bân'],
  },
  'loc_song_tien': {
    entityId: 'loc_song_tien',
    canonicalName: 'sông Tiền',
    type: 'LOCATION',
    aliases: ['Sông Tiền'],
  },
  'loc_thuan_hoa': {
    entityId: 'loc_thuan_hoa',
    canonicalName: 'Thuận Hóa',
    type: 'LOCATION',
    aliases: ['xứ Thuận Hóa'],
  },
  'loc_ha_dong': {
    entityId: 'loc_ha_dong',
    canonicalName: 'Hà Đông',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_tan_an': {
    entityId: 'loc_tan_an',
    canonicalName: 'Tân An',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_ai_chi_lang': {
    entityId: 'loc_ai_chi_lang',
    canonicalName: 'ải Chi Lăng',
    type: 'LOCATION',
    aliases: ['Ải Chi Lăng', 'Chi Lăng'],
  },
  'loc_van_mieu_quoc_tu_giam': {
    entityId: 'loc_van_mieu_quoc_tu_giam',
    canonicalName: 'Văn Miếu Quốc Tử Giám',
    type: 'LOCATION',
    aliases: ['Văn Miếu - Quốc Tử Giám', 'Văn Miếu'],
  },
  'loc_thanh_co_loa': {
    entityId: 'loc_thanh_co_loa',
    canonicalName: 'thành Cổ Loa',
    type: 'LOCATION',
    aliases: ['Cổ Loa'],
  },
  'loc_thanh_nha_ho': {
    entityId: 'loc_thanh_nha_ho',
    canonicalName: 'Thành nhà Hồ',
    type: 'LOCATION',
    aliases: ['Thành Tây Đô', 'thành Tây Đô', 'Tây Đô', 'thành nhà Hồ'],
  },
  'loc_tay_do': {
    entityId: 'loc_tay_do',
    canonicalName: 'Tây Đô',
    type: 'LOCATION',
    aliases: ['đất Tây Đô', 'Tây Đô', 'thành Tây Đô'],
  },
  'loc_dien_bien_phu': {
    entityId: 'loc_dien_bien_phu',
    canonicalName: 'Điện Biên Phủ',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_song_bach_dang': {
    entityId: 'loc_song_bach_dang',
    canonicalName: 'sông Bạch Đằng',
    type: 'LOCATION',
    aliases: ['Bạch Đằng'],
  },
  'loc_song_nhu_nguyet': {
    entityId: 'loc_song_nhu_nguyet',
    canonicalName: 'sông Như Nguyệt',
    type: 'LOCATION',
    aliases: ['Như Nguyệt'],
  },
  'loc_song_gianh': {
    entityId: 'loc_song_gianh',
    canonicalName: 'sông Gianh',
    type: 'LOCATION',
    aliases: ['Sông Gianh'],
  },
  'loc_quang_tri': {
    entityId: 'loc_quang_tri',
    canonicalName: 'Quảng Trị',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_quang_binh': {
    entityId: 'loc_quang_binh',
    canonicalName: 'Quảng Bình',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_da_nang': {
    entityId: 'loc_da_nang',
    canonicalName: 'Đà Nẵng',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_go_cong': {
    entityId: 'loc_go_cong',
    canonicalName: 'Gò Công',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_ben_tre': {
    entityId: 'loc_ben_tre',
    canonicalName: 'Bến Tre',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_yen_bai': {
    entityId: 'loc_yen_bai',
    canonicalName: 'Yên Bái',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_yen_tu': {
    entityId: 'loc_yen_tu',
    canonicalName: 'Yên Tử',
    type: 'LOCATION',
    aliases: ['núi Yên Tử', 'Núi Yên Tử'],
  },
  'loc_lam_son': {
    entityId: 'loc_lam_son',
    canonicalName: 'Lam Sơn',
    type: 'LOCATION',
    aliases: ['đất Lam Sơn'],
  },
  'loc_vinh_loc': {
    entityId: 'loc_vinh_loc',
    canonicalName: 'Vĩnh Lộc',
    type: 'LOCATION',
    aliases: ['huyện Vĩnh Lộc'],
  },
  'loc_vinh_an': {
    entityId: 'loc_vinh_an',
    canonicalName: 'Vĩnh An',
    type: 'LOCATION',
    aliases: ['châu Vĩnh An'],
  },
  'loc_bac_ha': {
    entityId: 'loc_bac_ha',
    canonicalName: 'Bắc Hà',
    type: 'LOCATION',
    aliases: ['đất Bắc Hà'],
  },
  'loc_dien_bien': {
    entityId: 'loc_dien_bien',
    canonicalName: 'Điện Biên',
    type: 'LOCATION',
    aliases: ['tỉnh Điện Biên', 'thung lũng Mường Thanh', 'Mường Thanh'],
  },
  'loc_son_tra': {
    entityId: 'loc_son_tra',
    canonicalName: 'bán đảo Sơn Trà',
    type: 'LOCATION',
    aliases: ['Bán đảo Sơn Trà', 'Sơn Trà'],
  },
  'loc_song_ben_hai': {
    entityId: 'loc_song_ben_hai',
    canonicalName: 'sông Bến Hải',
    type: 'LOCATION',
    aliases: ['Sông Bến Hải', 'Bến Hải'],
  },
  'loc_trung_ky': {
    entityId: 'loc_trung_ky',
    canonicalName: 'Trung Kỳ',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_dang_trong': {
    entityId: 'loc_dang_trong',
    canonicalName: 'Đàng Trong',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_dang_ngoai': {
    entityId: 'loc_dang_ngoai',
    canonicalName: 'Đàng Ngoài',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_tay_son': {
    entityId: 'loc_tay_son',
    canonicalName: 'ấp Tây Sơn',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_me_linh': {
    entityId: 'loc_me_linh',
    canonicalName: 'Mê Linh',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_soc_son': {
    entityId: 'loc_soc_son',
    canonicalName: 'núi Sóc Sơn',
    type: 'LOCATION',
    aliases: ['Sóc Sơn', 'núi Sóc'],
  },
  'loc_xu_doai': {
    entityId: 'loc_xu_doai',
    canonicalName: 'xứ Đoài',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_thanh_luy_lau': {
    entityId: 'loc_thanh_luy_lau',
    canonicalName: 'Thành cổ Luy Lâu',
    type: 'LOCATION',
    aliases: ['Luy Lâu', 'thành Luy Lâu'],
  },
  'loc_giao_chi': {
    entityId: 'loc_giao_chi',
    canonicalName: 'Giao Chỉ',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_long_bien': {
    entityId: 'loc_long_bien',
    canonicalName: 'Long Biên',
    type: 'LOCATION',
    aliases: ['thành Long Biên', 'Thành Long Biên'],
  },
  'loc_hat_mon': {
    entityId: 'loc_hat_mon',
    canonicalName: 'cửa sông Hát Môn',
    type: 'LOCATION',
    aliases: ['Hát Môn', 'sông Hát'],
  },
  'loc_dam_da_trach': {
    entityId: 'loc_dam_da_trach',
    canonicalName: 'đầm Dạ Trạch',
    type: 'LOCATION',
    aliases: ['Dạ Trạch'],
  },
  'loc_chua_mot_cot': {
    entityId: 'loc_chua_mot_cot',
    canonicalName: 'Chùa Một Cột',
    type: 'LOCATION',
    aliases: ['chùa Diên Hựu', 'Diên Hựu tự'],
  },
  'loc_ung_chau': {
    entityId: 'loc_ung_chau',
    canonicalName: 'thành Ung Châu',
    type: 'LOCATION',
    aliases: ['Ung Châu'],
  },
  'loc_dong_bo_dau': {
    entityId: 'loc_dong_bo_dau',
    canonicalName: 'Đông Bộ Đầu',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_chuong_duong': {
    entityId: 'loc_chuong_duong',
    canonicalName: 'Chương Dương',
    type: 'LOCATION',
    aliases: ['bến Chương Dương'],
  },
  'loc_thanh_da_bang': {
    entityId: 'loc_thanh_da_bang',
    canonicalName: 'Thành Đa Bang',
    type: 'LOCATION',
    aliases: ['Đa Bang', 'thành Đa Bang'],
  },
  'loc_ba_vi': {
    entityId: 'loc_ba_vi',
    canonicalName: 'Ba Vì',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_lung_nhai': {
    entityId: 'loc_lung_nhai',
    canonicalName: 'Lũng Nhai',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_nui_chi_linh': {
    entityId: 'loc_nui_chi_linh',
    canonicalName: 'núi Chí Linh',
    type: 'LOCATION',
    aliases: ['Chí Linh'],
  },
  'loc_le_chi_vien': {
    entityId: 'loc_le_chi_vien',
    canonicalName: 'Lệ Chi Viên',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_gia_binh': {
    entityId: 'loc_gia_binh',
    canonicalName: 'Gia Bình',
    type: 'LOCATION',
    aliases: ['huyện Gia Bình'],
  },
  'loc_luy_thay': {
    entityId: 'loc_luy_thay',
    canonicalName: 'Lũy Thầy',
    type: 'LOCATION',
    aliases: ['Lũy Đào Duy Từ'],
  },
  'loc_hoi_an': {
    entityId: 'loc_hoi_an',
    canonicalName: 'Hội An',
    type: 'LOCATION',
    aliases: ['đô thị cổ Hội An', 'phố cổ Hội An'],
  },
  'loc_pho_hien': {
    entityId: 'loc_pho_hien',
    canonicalName: 'Phố Hiến',
    type: 'LOCATION',
    aliases: ['thương cảng Phố Hiến'],
  },
  'loc_tam_diep': {
    entityId: 'loc_tam_diep',
    canonicalName: 'Tam Điệp',
    type: 'LOCATION',
    aliases: ['phòng tuyến Tam Điệp'],
  },
  'loc_song_huong': {
    entityId: 'loc_song_huong',
    canonicalName: 'sông Hương',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_hoang_sa': {
    entityId: 'loc_hoang_sa',
    canonicalName: 'quần đảo Hoàng Sa',
    type: 'LOCATION',
    aliases: ['Hoàng Sa'],
  },
  'loc_song_vam_co_dong': {
    entityId: 'loc_song_vam_co_dong',
    canonicalName: 'sông Vàm Cỏ Đông',
    type: 'LOCATION',
    aliases: ['Vàm Cỏ Đông'],
  },
  'loc_bac_giang': {
    entityId: 'loc_bac_giang',
    canonicalName: 'Bắc Giang',
    type: 'LOCATION',
    aliases: ['Yên Thế'],
  },
  'loc_buon_ma_thuot': {
    entityId: 'loc_buon_ma_thuot',
    canonicalName: 'Buôn Ma Thuột',
    type: 'LOCATION',
    aliases: ['thị xã Buôn Ma Thuột'],
  },
  'loc_cau_my_thuan': {
    entityId: 'loc_cau_my_thuan',
    canonicalName: 'Cầu Mỹ Thuận',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_thanh_dia_my_son': {
    entityId: 'loc_thanh_dia_my_son',
    canonicalName: 'Thánh địa Mỹ Sơn',
    type: 'LOCATION',
    aliases: ['Mỹ Sơn'],
  },
  'loc_thap_ba_po_nagar': {
    entityId: 'loc_thap_ba_po_nagar',
    canonicalName: 'Tháp Bà Po Nagar',
    type: 'LOCATION',
    aliases: ['tháp Po Nagar', 'Po Nagar'],
  },
  'loc_nha_trang': {
    entityId: 'loc_nha_trang',
    canonicalName: 'Nha Trang',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_khanh_hoa': {
    entityId: 'loc_khanh_hoa',
    canonicalName: 'Khánh Hòa',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_di_chi_oc_eo': {
    entityId: 'loc_di_chi_oc_eo',
    canonicalName: 'Di chỉ Văn hóa Óc Eo',
    type: 'LOCATION',
    aliases: ['Óc Eo', 'Văn hóa Óc Eo'],
  },
  'loc_ba_the': {
    entityId: 'loc_ba_the',
    canonicalName: 'Ba Thê',
    type: 'LOCATION',
    aliases: ['núi Ba Thê'],
  },
  'loc_an_giang': {
    entityId: 'loc_an_giang',
    canonicalName: 'An Giang',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_quang_nam': {
    entityId: 'loc_quang_nam',
    canonicalName: 'Quảng Nam',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_ha_tinh': {
    entityId: 'loc_ha_tinh',
    canonicalName: 'Hà Tĩnh',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_hung_yen': {
    entityId: 'loc_hung_yen',
    canonicalName: 'Hưng Yên',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_bac_ninh': {
    entityId: 'loc_bac_ninh',
    canonicalName: 'Bắc Ninh',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_cao_bang': {
    entityId: 'loc_cao_bang',
    canonicalName: 'Cao Bằng',
    type: 'LOCATION',
    aliases: [],
  },
  'loc_linh_nam': {
    entityId: 'loc_linh_nam',
    canonicalName: 'Lĩnh Nam',
    type: 'LOCATION',
    aliases: ['đất Lĩnh Nam'],
  },
  'loc_mien_nam': {
    entityId: 'loc_mien_nam',
    canonicalName: 'miền Nam',
    type: 'LOCATION',
    aliases: ['phía Nam', 'miền Nam Việt Nam'],
  },
  'loc_lam_kinh': {
    entityId: 'loc_lam_kinh',
    canonicalName: 'Lam Kinh',
    type: 'LOCATION',
    aliases: ['Tây Kinh Lam Kinh'],
  },
  'loc_dai_la': {
    entityId: 'loc_thang_long',
    canonicalName: 'thành Đại La',
    type: 'LOCATION',
    aliases: ['Đại La', 'thành Đại La'],
  },
  'loc_hang_xom_trai': {
    entityId: 'loc_hang_xom_trai',
    canonicalName: 'Hang Xóm Trại',
    type: 'LOCATION',
    aliases: ['di chỉ Hang Xóm Trại'],
  },
  'loc_mai_da_lang_vanh': {
    entityId: 'loc_mai_da_lang_vanh',
    canonicalName: 'Mái đá Làng Vành',
    type: 'LOCATION',
    aliases: ['di chỉ Mái đá Làng Vành'],
  },
  'loc_sa_huynh': {
    entityId: 'loc_sa_huynh',
    canonicalName: 'Sa Huỳnh',
    type: 'LOCATION',
    aliases: ['Khu mộ chum Sa Huỳnh', 'di chỉ Sa Huỳnh'],
  },
  'loc_ai_nam_quan': {
    entityId: 'loc_ai_nam_quan',
    canonicalName: 'ải Nam Quan',
    type: 'LOCATION',
    aliases: ['Ải Nam Quan'],
  },
  'loc_yen_kinh': {
    entityId: 'loc_yen_kinh',
    canonicalName: 'Yên Kinh',
    type: 'LOCATION',
    aliases: ['kinh đô Yên Kinh'],
  },
  'loc_thi_nai': {
    entityId: 'loc_thi_nai',
    canonicalName: 'đầm Thị Nại',
    type: 'LOCATION',
    aliases: ['cửa Thị Nại', 'Thị Nại'],
  },
  'loc_phung_nguyen': {
    entityId: 'loc_phung_nguyen',
    canonicalName: 'Phùng Nguyên',
    type: 'LOCATION',
    aliases: ['di chỉ Phùng Nguyên', 'Văn hóa Phùng Nguyên', 'văn hoá Phùng Nguyên'],
  },
  'loc_dong_dau': {
    entityId: 'loc_dong_dau',
    canonicalName: 'Đồng Đậu',
    type: 'LOCATION',
    aliases: ['di chỉ Đồng Đậu', 'Văn hóa Đồng Đậu', 'văn hoá Đồng Đậu'],
  },
  'loc_go_mun': {
    entityId: 'loc_go_mun',
    canonicalName: 'Gò Mun',
    type: 'LOCATION',
    aliases: ['di chỉ Gò Mun', 'Văn hóa Gò Mun', 'văn hoá Gò Mun'],
  },
  'loc_ba_dinh': {
    entityId: 'loc_ba_dinh',
    canonicalName: 'Quảng trường Ba Đình',
    type: 'LOCATION',
    aliases: ['Quảng trường Ba Đình', 'quảng trường Ba Đình', 'quận Ba Đình', 'Ba Đình'],
  },
  'loc_da_trach': {
    entityId: 'loc_da_trach',
    canonicalName: 'Dạ Trạch',
    type: 'LOCATION',
    aliases: ['đầm Dạ Trạch', 'Đầm Dạ Trạch'],
  },
  'loc_can_tho': {
    entityId: 'loc_can_tho',
    canonicalName: 'Cần Thơ',
    type: 'LOCATION',
    aliases: ['thành phố Cần Thơ', 'tỉnh Cần Thơ', 'Cần Thơ'],
  },
  'loc_nha_rong': {
    entityId: 'loc_nha_rong',
    canonicalName: 'bến Nhà Rồng',
    type: 'LOCATION',
    aliases: ['Nhà Rồng', 'Bến Nhà Rồng', 'Bến Cảng Nhà Rồng', 'bến cảng Nhà Rồng'],
  },
  'loc_chi_linh': {
    entityId: 'loc_chi_linh',
    canonicalName: 'Chí Linh',
    type: 'LOCATION',
    aliases: ['núi Chí Linh', 'thành phố Chí Linh'],
  },
  'loc_hoa_binh': {
    entityId: 'loc_hoa_binh',
    canonicalName: 'Hòa Bình',
    type: 'LOCATION',
    aliases: ['tỉnh Hòa Bình'],
  },
  'loc_nhat_ban': {
    entityId: 'loc_nhat_ban',
    canonicalName: 'Nhật Bản',
    type: 'LOCATION',
    aliases: ['nước Nhật'],
  },
  'loc_tan_trao': {
    entityId: 'loc_tan_trao',
    canonicalName: 'Tân Trào',
    type: 'LOCATION',
    aliases: ['chiến khu Tân Trào'],
  },
  'loc_thua_thien_hue': {
    entityId: 'loc_thua_thien_hue',
    canonicalName: 'Thừa Thiên Huế',
    type: 'LOCATION',
    aliases: ['tỉnh Thừa Thiên Huế', 'Thừa Thiên - Huế'],
  },
  'loc_tien_giang': {
    entityId: 'loc_tien_giang',
    canonicalName: 'Tiền Giang',
    type: 'LOCATION',
    aliases: ['sông Tiền Giang', 'tỉnh Tiền Giang'],
  },
};

/**
 * Normalizes text string for entity lookup (lowercase, trimmed, strip redundant punctuation)
 */
function normalizeKey(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFC')
    .replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, '')
    .trim();
}

/**
 * Resolves historical location mapping across eras (SAME_AS_LOCATION)
 */
export function resolveLocationMapping(locationName: string): HistoricalLocationMapping | undefined {
  const normInput = normalizeKey(locationName);
  return HISTORICAL_LOCATION_MAPPINGS.find(
    (m) => normalizeKey(m.historicalName) === normInput || normalizeKey(m.canonicalModernName) === normInput
  );
}
