/**
 * Historical Person Dictionary (SSOT)
 */
import type { HistoricalEntityInfo } from './types.js';

export const HISTORICAL_PERSON_DICTIONARY: Record<string, HistoricalEntityInfo> = {
  'person_quang_trung': {
    entityId: 'person_quang_trung',
    canonicalName: 'Quang Trung',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Huệ', 'Hồ Thơm', 'Bắc Bình Vương', 'Vua Quang Trung', 'Quang Trung Hoàng Đế', 'Long Nhương Tướng Quân', 'Long Nhượng Tướng Quân', 'Anh hùng áo vải'],
    timeRange: { start: 1753, end: 1792 },
    dynasty: 'Nhà Tây Sơn',
    namingMetadata: {
      birthName: 'Hồ Thơm',
      courtesyOrCommonName: 'Nguyễn Huệ',
      preReignTitles: ['Long Nhương Tướng Quân', 'Bắc Bình Vương'],
      reignEra: 'Quang Trung',
      reignPeriod: { start: 1788, end: 1792 },
      familyLineage: {
        father: 'Hồ Phi Phúc',
        mother: 'Nguyễn Thị Đồng',
        siblings: ['Nguyễn Nhạc (Tây Sơn Vương)', 'Nguyễn Lữ (Đông Định Vương)'],
        spouses: ['Phạm Thị Liên', 'Bùi Thị Nhạn', 'Lê Ngọc Hân (Công chúa Ngọc Hân)'],
        children: ['Quang Toản (Cảnh Thịnh Hoàng đế)'],
      },
      misconceptions: [
        {
          id: 'misc_quang_trung_cot_cheo',
          triggerKeywords: ['cột chèo', 'anh em cột chèo', 'anh em'],
          explanation:
            'Giai thoại "anh em cột chèo" trong lịch sử thực chất là nhắc đến mối quan hệ giữa Nguyễn Huệ và Nguyễn Ánh (Gia Long), do cả hai cùng kết duyên với hai chị em công chúa con vua Lê Hiển Tông là Lê Ngọc Hân và Lê Ngọc Bình. Tuyệt đối không gán ghép cụm từ này cho Quang Trung và Nguyễn Huệ. Hai người anh em ruột cùng dựng cờ khởi nghĩa Tây Sơn với Nguyễn Huệ là Nguyễn Nhạc và Nguyễn Lữ (Tây Sơn tam kiệt).',
          relatedEntityIds: ['person_gia_long', 'person_quang_trung'],
        },
      ],
    },
  },
  'person_nguyen_nhac': {
    entityId: 'person_nguyen_nhac',
    canonicalName: 'Nguyễn Nhạc',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tây Sơn Vương', 'Thái Đức Hoàng Đế', 'Vua Thái Đức'],
    timeRange: { start: 1743, end: 1793 },
    dynasty: 'Nhà Tây Sơn',
    namingMetadata: {
      birthName: 'Hồ Nhạc',
      courtesyOrCommonName: 'Nguyễn Nhạc',
      preReignTitles: ['Tây Sơn Vương'],
      reignEra: 'Thái Đức',
      reignPeriod: { start: 1778, end: 1793 },
      familyLineage: {
        father: 'Hồ Phi Phúc',
        mother: 'Nguyễn Thị Đồng',
        siblings: ['Nguyễn Huệ (Quang Trung Hoàng đế)', 'Nguyễn Lữ (Đông Định Vương)'],
      },
    },
  },
  'person_kinh_duong_vuong': {
    entityId: 'person_kinh_duong_vuong',
    canonicalName: 'Kinh Dương Vương',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lộc Tục', 'Vua Kinh Dương Vương'],
    timeRange: { start: -2879, end: -2793 },
    dynasty: 'Hồng Bàng',
  },
  'person_lac_long_quan': {
    entityId: 'person_lac_long_quan',
    canonicalName: 'Lạc Long Quân',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sùng Lãm', 'Bố Lạc Long Quân'],
    timeRange: { start: -2793, end: -2524 },
    dynasty: 'Hồng Bàng',
  },
  'person_tran_hung_dao': {
    entityId: 'person_tran_hung_dao',
    canonicalName: 'Trần Hưng Đạo',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trần Quốc Tuấn', 'Hưng Đạo Đại Vương', 'Hưng Đạo Vương', 'Đức Thánh Trần'],
    timeRange: { start: 1228, end: 1300 },
    dynasty: 'Nhà Trần',
    namingMetadata: {
      birthName: 'Trần Quốc Tuấn',
      preReignTitles: ['Quốc công Tiết chế'],
      templeName: 'Hưng Đạo Đại Vương',
      familyLineage: {
        father: 'An Sinh Vương Trần Liễu',
        mother: 'Thiện Đạo Quốc mẫu',
        siblings: ['Tuệ Trung Thượng Sĩ (Trần Tung)', 'Doãn Hiến vương Trần Quốc Khang'],
        spouses: ['Thiên Thành Công chúa'],
        children: ['Trần Quốc Nghiễn (Hưng Vũ vương)', 'Trần Quốc Hiện (Hưng Hiến vương)', 'Trần Quốc Tảng (Hưng Nhượng vương)', 'Trần Quốc Ánh (Hưng Trí vương)', 'Bảo Thánh Hoàng hậu Trần Khâm'],
      },
    },
  },
  'person_le_loi': {
    entityId: 'person_le_loi',
    canonicalName: 'Lê Lợi',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Thái Tổ', 'Bình Định Vương', 'Vua Lê Lợi', 'Thái Tổ Hoàng đế'],
    timeRange: { start: 1385, end: 1433 },
    dynasty: 'Nhà Hậu Lê',
    namingMetadata: {
      birthName: 'Lê Lợi',
      preReignTitles: ['Bình Định Vương'],
      reignEra: 'Thuận Thiên',
      templeName: 'Lê Thái Tổ',
      reignPeriod: { start: 1428, end: 1433 },
      familyLineage: {
        father: 'Lê Khoáng (Lê Tuyên Tổ)',
        mother: 'Trịnh Thị Ngọc Thương (Trinh Từ Hoàng thái hậu)',
        siblings: ['Lê Học (Chiêu Tằng đại vương)', 'Lê Trừ (Hoằng Dụ đại vương)'],
        children: ['Lê Tư Tề (Quận vương)', 'Lê Thái Tông (Lê Nguyên Long)'],
      },
    },
  },
  'person_ngo_quyen': {
    entityId: 'person_ngo_quyen',
    canonicalName: 'Ngô Quyền',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tiền Ngô Vương', 'Vua Ngô Quyền'],
    timeRange: { start: 897, end: 944 },
    dynasty: 'Nhà Ngô / Thời kỳ Tự chủ',
    namingMetadata: {
      birthName: 'Ngô Quyền',
      preReignTitles: ['Tiền Ngô Vương'],
      familyLineage: {
        father: 'Ngô Mân',
        spouses: ['Dương Như Ngọc (Dương thị)'],
      },
      adversaries: ['Kiều Công Tiễn', 'Lưu Hoằng Thao', 'Lưu Hoằng Tháo', 'Lưu Cung'],
    },
  },
  'person_kieu_cong_tien': {
    entityId: 'person_kieu_cong_tien',
    canonicalName: 'Kiều Công Tiễn',
    type: 'HISTORICAL_PERSON',
    aliases: ['Công Tiễn', 'Kiều Công Tiển'],
    timeRange: { start: 870, end: 938 },
    dynasty: 'Thời kỳ Tự chủ',
    namingMetadata: {
      birthName: 'Kiều Công Tiễn',
      adversaries: ['Ngô Quyền', 'Dương Đình Nghệ'],
    },
  },
  'person_luu_hoang_thao': {
    entityId: 'person_luu_hoang_thao',
    canonicalName: 'Lưu Hoằng Thao',
    type: 'HISTORICAL_PERSON',
    aliases: ['Hoằng Thao', 'Lưu Hoằng Tháo', 'Hoằng Tháo', 'Vạn Vương Thao'],
    timeRange: { start: 900, end: 938 },
    dynasty: 'Nam Hán (Thời kỳ Tự chủ)',
    namingMetadata: {
      birthName: 'Lưu Hoằng Thao',
      adversaries: ['Ngô Quyền'],
      familyLineage: {
        father: 'Lưu Cung (Nam Hán Cao Tổ)',
      },
    },
  },
  'person_ly_thai_to': {
    entityId: 'person_ly_thai_to',
    canonicalName: 'Lý Thái Tổ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Công Uẩn', 'Vua Lý Thái Tổ', 'Thái Tổ Hoàng đế'],
    timeRange: { start: 974, end: 1028 },
    dynasty: 'Nhà Lý',
    namingMetadata: {
      birthName: 'Lý Công Uẩn',
      reignEra: 'Thuận Thiên',
      templeName: 'Lý Thái Tổ',
      reignPeriod: { start: 1009, end: 1028 },
      familyLineage: {
        father: 'Hiển Khánh Vương',
        mother: 'Phạm Thị',
        children: ['Lý Thái Tông (Lý Phật Mã)'],
      },
    },
  },
  'person_dinh_tien_hoang': {
    entityId: 'person_dinh_tien_hoang',
    canonicalName: 'Đinh Tiên Hoàng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đinh Bộ Lĩnh', 'Vạn Thắng Vương', 'Đinh Tiên Hoàng Đế'],
    timeRange: { start: 924, end: 979 },
    dynasty: 'Nhà Đinh',
    namingMetadata: {
      birthName: 'Đinh Bộ Lĩnh',
      preReignTitles: ['Vạn Thắng Vương'],
      reignEra: 'Thái Bình',
      templeName: 'Đinh Tiên Hoàng',
      reignPeriod: { start: 968, end: 979 },
      familyLineage: {
        father: 'Đinh Công Trứ',
        mother: 'Đàm Thị',
        spouses: ['Dương Vân Nga (Đại Thắng Minh Hoàng Hậu)'],
        children: ['Đinh Liễn (Nam Việt vương)', 'Đinh Hạng Lang', 'Đinh Toàn (Đinh Phế Đế)'],
      },
    },
  },
  'person_nguyen_trai': {
    entityId: 'person_nguyen_trai',
    canonicalName: 'Nguyễn Trãi',
    type: 'HISTORICAL_PERSON',
    aliases: ['Ức Trai', 'Quan Trãi'],
    timeRange: { start: 1380, end: 1442 },
    dynasty: 'Nhà Hậu Lê',
  },
  'person_vo_nguyen_giap': {
    entityId: 'person_vo_nguyen_giap',
    canonicalName: 'Võ Nguyên Giáp',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đại tướng Võ Nguyên Giáp', 'Tướng Giáp', 'Anh Văn'],
    timeRange: { start: 1911, end: 2013 },
    dynasty: 'Thời kỳ Hiện đại',
    namingMetadata: {
      adversaries: ['Christian de Castries', 'De Castries', 'Henri Navarre', 'Đờ Cát', 'Tướng De Castries'],
    },
  },
  'person_le_dai_hanh': {
    entityId: 'person_le_dai_hanh',
    canonicalName: 'Lê Đại Hành',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Hoàn', 'Vua Lê Đại Hành', 'Lê Đại Hành Hoàng Đế'],
    timeRange: { start: 941, end: 1005 },
    dynasty: 'Nhà Tiền Lê',
    misconceptions: [
      {
        id: 'misc_le_hoan_ly_dynasty',
        triggerKeywords: ['nhà lý', 'thuộc nhà lý', 'vua nhà lý', 'triều lý', 'triều nhà lý'],
        explanation:
          'Lê Hoàn (Lê Đại Hành) là vị hoàng đế sáng lập triều Tiền Lê (trị vì 980 - 1005), lãnh đạo quân dân Đại Cồ Việt đánh tan quân Tống xâm lược trong trận Bạch Đằng năm 981. Triều Lý thành lập năm 1009 bởi Lý Thái Tổ (Lý Công Uẩn), sau khi triều Tiền Lê kết thúc, hoàn toàn không liên quan đến chiến thắng năm 981.',
        relatedEntityIds: ['person_le_dai_hanh', 'person_ly_thai_to'],
      },
    ],
    namingMetadata: {
      birthName: 'Lê Hoàn',
      templeName: 'Lê Đại Hành',
      reignPeriod: { start: 980, end: 1005 },
      familyLineage: {
        father: 'Lê Mịch',
        mother: 'Đặng Thị',
        spouses: ['Dương Vân Nga (Đại Thắng Minh Hoàng Hậu)'],
        children: ['Lê Long Việt (Lê Trung Tông)', 'Lê Long Đĩnh (Lê Ngọa Triều)'],
      },
      adversaries: ['Hầu Nhân Bảo', 'Triệu Phụng Huân', 'Quách Quân Biện'],
    },
  },
  'person_duong_van_nga': {
    entityId: 'person_duong_van_nga',
    canonicalName: 'Dương Vân Nga',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thái hậu Dương Vân Nga', 'Dương Thái hậu', 'Đại Thắng Minh Hoàng Hậu'],
    timeRange: { start: 952, end: 1000 },
    dynasty: 'Nhà Đinh',
    namingMetadata: {
      familyLineage: {
        spouses: ['Đinh Tiên Hoàng', 'Lê Đại Hành'],
        children: ['Đinh Toàn (Đinh Phế Đế)'],
      },
    },
  },
  'person_hau_nhan_bao': {
    entityId: 'person_hau_nhan_bao',
    canonicalName: 'Hầu Nhân Bảo',
    type: 'HISTORICAL_PERSON',
    aliases: ['tướng Hầu Nhân Bảo', 'Hầu Nhân Bảo'],
    timeRange: { start: 935, end: 981 },
    dynasty: 'Nhà Tiền Lê',
  },
  'person_thoat_hoan': {
    entityId: 'person_thoat_hoan',
    canonicalName: 'Thoát Hoan',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trấn Nam Vương Thoát Hoan', 'Thoát Hoan'],
    timeRange: { start: 1250, end: 1301 },
    dynasty: 'Nhà Trần',
  },
  'person_quach_quy': {
    entityId: 'person_quach_quy',
    canonicalName: 'Quách Quỳ',
    type: 'HISTORICAL_PERSON',
    aliases: ['tướng Quách Quỳ', 'Quách Quỳ'],
    timeRange: { start: 1022, end: 1088 },
    dynasty: 'Nhà Lý',
  },
  'person_ton_si_nghi': {
    entityId: 'person_ton_si_nghi',
    canonicalName: 'Tôn Sĩ Nghị',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tổng đốc Tôn Sĩ Nghị', 'Tôn Sĩ Nghị'],
    timeRange: { start: 1720, end: 1796 },
    dynasty: 'Thời Tây Sơn',
  },
  'person_sam_nghi_dong': {
    entityId: 'person_sam_nghi_dong',
    canonicalName: 'Sầm Nghi Đống',
    type: 'HISTORICAL_PERSON',
    aliases: ['tướng Sầm Nghi Đống', 'Thái thú Sầm Nghi Đống', 'Sầm Nghi Đống'],
    timeRange: { start: 1740, end: 1789 },
    dynasty: 'Thời Tây Sơn',
  },
  'person_tran_ba_tien': {
    entityId: 'person_tran_ba_tien',
    canonicalName: 'Trần Bá Tiên',
    type: 'HISTORICAL_PERSON',
    aliases: ['tướng Trần Bá Tiên', 'Trần Bá Tiên'],
    timeRange: { start: 503, end: 559 },
    dynasty: 'Thời Tiền Lý',
  },
  'person_tieu_tu': {
    entityId: 'person_tieu_tu',
    canonicalName: 'Tiêu Tư',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thứ sử Tiêu Tư', 'Tiêu Tư'],
    timeRange: { start: 500, end: 550 },
    dynasty: 'Thời Tiền Lý',
  },
  'person_luc_dan': {
    entityId: 'person_luc_dan',
    canonicalName: 'Lục Dận',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thứ sử Lục Dận', 'tướng Lục Dận', 'Lục Dận'],
    timeRange: { start: 200, end: 260 },
    dynasty: 'Thời kỳ Bắc thuộc',
  },
  'person_ba_trieu': {
    entityId: 'person_ba_trieu',
    canonicalName: 'Bà Triệu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Triệu Thị Trinh', 'Triệu Trinh Nương', 'Nhất Lục Nương'],
    timeRange: { start: 225, end: 248 },
    dynasty: 'Thời kỳ Bắc thuộc',
  },
  'person_hai_ba_trung': {
    entityId: 'person_hai_ba_trung',
    canonicalName: 'Hai Bà Trưng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Hai Bà Trưng', 'chị em Trưng Trắc Trưng Nhị'],
    timeRange: { start: 14, end: 43 },
    dynasty: 'Trưng Nữ Vương',
  },
  'person_trung_trac': {
    entityId: 'person_trung_trac',
    canonicalName: 'Trưng Trắc',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trưng Trắc', 'Bà Trưng Trắc', 'Trưng Nữ Vương', 'Trưng Hoàng Đế', 'Trưng Vương'],
    timeRange: { start: 14, end: 43 },
    dynasty: 'Trưng Nữ Vương',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trưng Trắc',
      courtesyOrCommonName: 'Bà Trưng Trắc',
      reignEra: 'Trưng Nữ Vương',
      reignPeriod: { start: 40, end: 43 },
      familyLineage: {
        siblings: ['Trưng Nhị'],
        spouses: ['Thi Sách'],
      },
      adversaries: ['Tô Định', 'Mã Viện'],
    },
  },
  'person_trung_nhi': {
    entityId: 'person_trung_nhi',
    canonicalName: 'Trưng Nhị',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trưng Nhị', 'Bà Trưng Nhị', 'Phó tướng Trưng Nhị'],
    timeRange: { start: 14, end: 43 },
    dynasty: 'Trưng Nữ Vương',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trưng Nhị',
      familyLineage: {
        siblings: ['Trưng Trắc'],
      },
      adversaries: ['Tô Định', 'Mã Viện'],
    },
  },
  'person_thi_sach': {
    entityId: 'person_thi_sach',
    canonicalName: 'Thi Sách',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thi Sách', 'con trai Lạc tướng Chu Diên'],
    timeRange: { start: 10, end: 40 },
    dynasty: 'Thời kỳ Bắc thuộc',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Thi Sách',
      familyLineage: {
        spouses: ['Trưng Trắc'],
      },
      adversaries: ['Tô Định'],
    },
  },
  'person_ly_thuong_kiet': {
    entityId: 'person_ly_thuong_kiet',
    canonicalName: 'Lý Thường Kiệt',
    type: 'HISTORICAL_PERSON',
    aliases: ['Ngô Tuấn', 'Thái úy Lý Thường Kiệt', 'Thái úy'],
    timeRange: { start: 1019, end: 1105 },
    dynasty: 'Nhà Lý',
  },
  'person_an_duong_vuong': {
    entityId: 'person_an_duong_vuong',
    canonicalName: 'An Dương Vương',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thục Phán', 'Thục Phán An Dương Vương', 'Thục Vương', 'Vua Thục', 'An Dương Vương'],
    timeRange: { start: -257, end: -208 },
    dynasty: 'Âu Lạc',
    isMythological: false,
    namingMetadata: {
      birthName: 'Thục Phán',
      reignEra: 'An Dương Vương',
      reignPeriod: { start: -257, end: -208 },
    },
  },
  'person_cao_lo': {
    entityId: 'person_cao_lo',
    canonicalName: 'Cao Lỗ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tướng quân Cao Lỗ', 'Đô Lỗ'],
    timeRange: { start: -257, end: -208 },
    dynasty: 'Âu Lạc',
  },
  'person_hung_vuong': {
    entityId: 'person_hung_vuong',
    canonicalName: 'Hùng Vương',
    type: 'HISTORICAL_PERSON',
    aliases: ['Vua Hùng', 'Vua Hùng Vương', 'Hùng Vương thứ 18'],
    timeRange: { start: -2524, end: -258 },
    dynasty: 'Hồng Bàng / Văn Lang',
    isMythological: true,
  },
  'person_than_kim_quy': {
    entityId: 'person_than_kim_quy',
    canonicalName: 'Thần Kim Quy',
    type: 'HISTORICAL_PERSON',
    aliases: ['Rùa Vàng', 'Thần Rùa Vàng', 'Kim Quy'],
    isMythological: true,
  },
  'person_thanh_giong': {
    entityId: 'person_thanh_giong',
    canonicalName: 'Thánh Gióng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Phù Đổng Thiên Vương', 'Gióng'],
    isMythological: true,
  },
  'person_son_tinh': {
    entityId: 'person_son_tinh',
    canonicalName: 'Sơn Tinh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tản Viên Sơn Thánh'],
    isMythological: true,
  },
  'person_thuy_tinh': {
    entityId: 'person_thuy_tinh',
    canonicalName: 'Thủy Tinh',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    isMythological: true,
  },
  'person_ly_nam_de': {
    entityId: 'person_ly_nam_de',
    canonicalName: 'Lý Nam Đế',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Bí', 'Vua Lý Nam Đế'],
    timeRange: { start: 503, end: 548 },
    dynasty: 'Nhà Tiền Lý / Vạn Xuân',
  },
  'person_trieu_da': {
    entityId: 'person_trieu_da',
    canonicalName: 'Triệu Đà',
    type: 'HISTORICAL_PERSON',
    aliases: ['Triệu Vũ Đế'],
    timeRange: { start: -257, end: -137 },
    dynasty: 'Nhà Triệu',
  },
  'person_tran_nhan_tong': {
    entityId: 'person_tran_nhan_tong',
    canonicalName: 'Trần Nhân Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Vua Trần Nhân Tông', 'Trúc Lâm Đại Đầu Đà'],
    timeRange: { start: 1258, end: 1308 },
    dynasty: 'Nhà Trần',
  },
  'person_ho_quy_ly': {
    entityId: 'person_ho_quy_ly',
    canonicalName: 'Hồ Quý Ly',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Quý Ly', 'Vua Hồ Quý Ly'],
    timeRange: { start: 1336, end: 1407 },
    dynasty: 'Nhà Hồ',
  },
  'person_tran_thiem_binh': {
    entityId: 'person_tran_thiem_binh',
    canonicalName: 'Trần Thiêm Bình',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Khang', 'Trần Khang', 'kẻ mạo danh Trần Thiêm Bình'],
    timeRange: { start: 1370, end: 1406 },
    dynasty: 'Nhà Trần',
    role: 'ADVERSARY',
    misconceptions: [
      {
        id: 'misc_tran_thiem_binh_usurpation',
        triggerKeywords: ['cướp ngôi', 'phế truất', 'thay thế', 'lật đổ', 'làm vua', 'bị phế', 'nhà trần'],
        explanation:
          'Người bị Hồ Quý Ly truất ngôi năm 1400 là vua Trần Thiếu Đế (vị vua cuối cùng của triều Trần). Trần Thiêm Bình (tên thật là Nguyễn Khang) là gia nô mạo xưng tôn thất nhà Trần chạy sang cầu viện nhà Minh mượn cớ xâm lược Đại Ngu, KHÔNG PHẢI là vua và KHÔNG PHẢI người bị Hồ Quý Ly cướp ngôi.',
        relatedEntityIds: ['person_ho_quy_ly', 'person_tran_thieu_de'],
      },
    ],
    namingMetadata: {
      birthName: 'Nguyễn Khang',
      courtesyOrCommonName: 'Trần Thiêm Bình',
    },
  },
  'person_ho_nguyen_trung': {
    entityId: 'person_ho_nguyen_trung',
    canonicalName: 'Hồ Nguyên Trừng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Trừng', 'Nam Ông', 'Tả tướng quốc Hồ Nguyên Trừng'],
    timeRange: { start: 1374, end: 1446 },
    dynasty: 'Nhà Hồ',
    namingMetadata: {
      birthName: 'Lê Trừng (sau đổi thành Hồ Nguyên Trừng)',
      courtesyOrCommonName: 'Nam Ông',
      familyLineage: {
        father: 'Hồ Quý Ly',
        siblings: ['Hồ Hán Thương'],
      },
      famousQuote: 'Thần không sợ đánh, chỉ sợ lòng dân không theo (Đại Việt Sử Ký Toàn Thư ghi nhận lời đáp vua Hồ Hán Thương năm 1405 trước họa xâm lăng của giặc Minh).',
      achievements: [
        'Sáng chế Súng thần cơ (Thần cơ sang pháo) - hỏa khí ưu việt hàng đầu thời phong kiến',
        'Tổng công trình sư xây dựng phòng tuyến sông Hồng, thành Đa Bang và đồn lũy kháng Minh',
        'Tác giả tác phẩm văn học Nam Ông mộng lục',
      ],
    },
  },
  'person_mac_dang_dung': {
    entityId: 'person_mac_dang_dung',
    canonicalName: 'Mạc Đăng Dung',
    type: 'HISTORICAL_PERSON',
    aliases: ['Mạc Thái Tổ', 'Vua Mạc Thái Tổ'],
    timeRange: { start: 1483, end: 1541 },
    dynasty: 'Nhà Mạc',
  },
  'person_nguyen_kim': {
    entityId: 'person_nguyen_kim',
    canonicalName: 'Nguyễn Kim',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thái sư Lương quốc công Nguyễn Kim'],
    timeRange: { start: 1468, end: 1545 },
    dynasty: 'Lê Trung Hưng',
  },
  'person_nguyen_hoang': {
    entityId: 'person_nguyen_hoang',
    canonicalName: 'Nguyễn Hoàng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chúa Tiên', 'Đoan Quốc Công'],
    timeRange: { start: 1525, end: 1613 },
    dynasty: 'Chúa Nguyễn',
  },
  'person_dao_duy_tu': {
    entityId: 'person_dao_duy_tu',
    canonicalName: 'Đào Duy Từ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lộc Khê hầu'],
    timeRange: { start: 1572, end: 1634 },
    dynasty: 'Chúa Nguyễn',
  },
  'person_gia_long': {
    entityId: 'person_gia_long',
    canonicalName: 'Gia Long',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Ánh', 'Vua Gia Long', 'Gia Long Hoàng Đế', 'Nguyễn Phúc Ánh'],
    timeRange: { start: 1762, end: 1820 },
    dynasty: 'Nhà Nguyễn',
    namingMetadata: {
      birthName: 'Nguyễn Phúc Ánh (Nguyễn Ánh)',
      courtesyOrCommonName: 'Vua Gia Long (vua sáng lập triều Nguyễn)',
      reignEra: 'Gia Long',
      templeName: 'Thế Tổ',
      reignPeriod: { start: 1802, end: 1820 },
      familyLineage: {
        father: 'Nguyễn Phúc Luân (Hiếu Khang Hoàng đế - Đệ nhị công tử)',
        mother: 'Nguyễn Thị Hoàn (Hiếu Khang Hoàng hậu)',
        children: ['Nguyễn Phúc Cảnh (Hoàng tử Cảnh)', 'Nguyễn Phúc Đảm (Vua Minh Mạng - người kế vị)'],
      },
      famousQuote: 'Đặt quốc hiệu Việt Nam năm 1804 và chính thức thực thi, khẳng định chủ quyền của vương triều tại hai quần đảo Hoàng Sa và Trường Sa.',
      achievements: [
        'Thống nhất giang sơn đất nước trọn vẹn từ Ải Nam Quan đến Mũi Cà Mau (1802)',
        'Xác lập quốc hiệu Việt Nam chính thức trên trường ngoại giao quốc tế (1804)',
        'Thiết lập hệ thống hành chính quy củ, ban hành bộ luật Hoàng Việt luật lệ (luật Gia Long)',
        'Xác lập và thực thi chủ quyền biển đảo liên tục tại hai quần đảo Hoàng Sa và Trường Sa',
      ],
      misconceptions: [
        {
          id: 'misc_gia_long_cot_cheo',
          triggerKeywords: ['cột chèo', 'anh em cột chèo', 'anh em'],
          explanation:
            'Gia Long và Nguyễn Ánh thực chất là cùng một người. Giai thoại "anh em cột chèo" trong lịch sử thực chất là nhắc đến mối quan hệ giữa Nguyễn Huệ (Quang Trung) và Nguyễn Ánh (Gia Long), do cả hai cùng kết duyên với hai chị em công chúa con vua Lê Hiển Tông là Lê Ngọc Hân và Lê Ngọc Bình. Tuyệt đối không gán ghép cụm từ này cho bản thân một nhân vật lịch sử.',
          relatedEntityIds: ['person_quang_trung', 'person_gia_long'],
        },
      ],
    },
  },
  'person_minh_mang': {
    entityId: 'person_minh_mang',
    canonicalName: 'Minh Mạng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Phúc Đảm', 'Vua Minh Mạng', 'Minh Mệnh'],
    timeRange: { start: 1791, end: 1841 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_tu_duc': {
    entityId: 'person_tu_duc',
    canonicalName: 'Tự Đức',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Phúc Thì', 'Nguyễn Phúc Hồng Nhậm', 'Vua Tự Đức', 'Tự Đức Hoàng Đế', 'Hoàng đế Tự Đức'],
    timeRange: { start: 1829, end: 1883 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_pham_van_dong': {
    entityId: 'person_pham_van_dong',
    canonicalName: 'Phạm Văn Đồng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thủ tướng Phạm Văn Đồng', 'Anh Tô'],
    timeRange: { start: 1906, end: 2000 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_lieu_thang': {
    entityId: 'person_lieu_thang',
    canonicalName: 'Liễu Thăng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tổng binh Liễu Thăng'],
    timeRange: { start: 1370, end: 1427 },
    dynasty: 'Nhà Minh',
  },
  'person_mai_thuc_loan': {
    entityId: 'person_mai_thuc_loan',
    canonicalName: 'Mai Thúc Loan',
    type: 'HISTORICAL_PERSON',
    aliases: ['Mai Hắc Đế', 'Vua Mai Hắc Đế'],
    timeRange: { start: 670, end: 722 },
    dynasty: 'Thời kỳ Bắc thuộc',
    namingMetadata: {
      birthName: 'Mai Thúc Loan',
      reignEra: 'Mai Hắc Đế',
      reignPeriod: { start: 713, end: 722 },
    },
  },
  'person_ho_chi_minh': {
    entityId: 'person_ho_chi_minh',
    canonicalName: 'Hồ Chí Minh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bác Hồ', 'Nguyễn Ái Quốc', 'Nguyễn Tất Thành', 'Chủ tịch Hồ Chí Minh', 'Cụ Hồ', 'Văn Ba', 'Lý Thụy', 'Thầu Chín'],
    timeRange: { start: 1890, end: 1969 },
    dynasty: 'Thời kỳ Hiện đại',
    namingMetadata: {
      archetype: 'MODERN_FIGURE',
      birthName: 'Nguyễn Sinh Cung (Nguyễn Sinh Côn)',
      courtesyOrCommonName: 'Nguyễn Tất Thành, Nguyễn Ái Quốc, Bác Hồ',
      periodAliases: [
        { period: '1890 - 1901 (thuở nhỏ)', name: 'Nguyễn Sinh Cung (Nguyễn Sinh Côn)' },
        { period: '1901 (khi bắt đầu đi học)', name: 'Nguyễn Tất Thành (do thân phụ Nguyễn Sinh Sắc đặt tên tự)' },
        { period: '1911 (khi lên tàu Latouche-Tréville xuất dương)', name: 'Văn Ba (Anh Ba)' },
        { period: '1919 - 1941 (hoạt động cách mạng quốc tế)', name: 'Nguyễn Ái Quốc' },
        { period: '1924 - 1927 (hoạt động tại Quảng Châu)', name: 'Lý Thụy' },
        { period: '1928 - 1929 (hoạt động tại Xiêm)', name: 'Thầu Chín' },
        { period: 'Từ 1941 (về nước lập Mặt trận Việt Minh và lãnh đạo cách mạng)', name: 'Hồ Chí Minh' },
        { period: 'Nhân dân tôn kính', name: 'Bác Hồ, Cụ Hồ' },
      ],
      totalAliasesEstimated: 'Khoảng 150 đến 175 tên gọi, bút danh, bí danh theo các công trình nghiên cứu chính thức của Bảo tàng Hồ Chí Minh và giới sử học',
    },
  },
  'person_le_do': {
    entityId: 'person_le_do',
    canonicalName: 'Lê Độ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Dậu', 'Anh hùng Lê Độ', 'Liệt sĩ Lê Độ', 'anh hùng Lê Độ'],
    timeRange: { start: 1941, end: 1965 },
    dynasty: 'Thời kỳ Hiện đại',
    namingMetadata: {
      archetype: 'MODERN_FIGURE',
      birthName: 'Lê Dậu',
      courtesyOrCommonName: 'Lê Độ',
      familyLineage: {
        father: 'Lê Duy Ban',
      },
    },
  },
  'person_tran_thu_do': {
    entityId: 'person_tran_thu_do',
    canonicalName: 'Trần Thủ Độ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thái sư Trần Thủ Độ'],
    timeRange: { start: 1194, end: 1264 },
    dynasty: 'Nhà Trần',
  },
  'person_tran_khanh_du': {
    entityId: 'person_tran_khanh_du',
    canonicalName: 'Trần Khánh Dư',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nhân Huệ Vương', 'Nhân Huệ Vương Trần Khánh Dư', 'tướng Trần Khánh Dư'],
    timeRange: { start: 1240, end: 1340 },
    dynasty: 'Nhà Trần',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trần Khánh Dư',
      courtesyOrCommonName: 'Nhân Huệ Vương',
      preReignTitles: ['Thượng tướng', 'Nhân Huệ Vương'],
    },
  },
  'person_tran_thua': {
    entityId: 'person_tran_thua',
    canonicalName: 'Trần Thừa',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thái thượng hoàng Trần Thừa', 'Trần Thái Tổ'],
    timeRange: { start: 1184, end: 1234 },
    dynasty: 'Nhà Trần',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trần Thừa',
      templeName: 'Trần Thái Tổ',
      reignEra: 'Thái thượng hoàng',
      familyLineage: {
        children: ['Trần Liễu', 'Trần Cảnh (Trần Thái Tông)', 'Trần Nhật Hiệu', 'Trần Bà Liệt'],
      },
    },
  },
  'person_tran_lieu': {
    entityId: 'person_tran_lieu',
    canonicalName: 'Trần Liễu',
    type: 'HISTORICAL_PERSON',
    aliases: ['An Sinh Vương', 'An Sinh Vương Trần Liễu', 'Phụng Càn Vương Trần Liễu', 'Yên Sinh Vương'],
    timeRange: { start: 1211, end: 1251 },
    dynasty: 'Nhà Trần',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trần Liễu',
      courtesyOrCommonName: 'An Sinh Vương',
      preReignTitles: ['Phụng Càn Vương', 'Hiển Hoàng', 'An Sinh Vương'],
      familyLineage: {
        father: 'Trần Thừa (Trần Thái Tổ)',
        siblings: ['Trần Cảnh (Trần Thái Tông)', 'Trần Nhật Hiệu', 'Trần Bà Liệt'],
        children: ['Trần Quốc Tuấn (Hưng Đạo Đại Vương)', 'Trần Doãn', 'Trần Tung (Tuệ Trung Thượng Sĩ)'],
      },
    },
  },
  'person_tran_thai_tong': {
    entityId: 'person_tran_thai_tong',
    canonicalName: 'Trần Thái Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trần Cảnh', 'Vua Trần Thái Tông'],
    timeRange: { start: 1218, end: 1277 },
    dynasty: 'Nhà Trần',
    namingMetadata: {
      archetype: 'FEUDAL_FIGURE',
      birthName: 'Trần Cảnh',
      templeName: 'Trần Thái Tông',
      reignEra: 'Kiến Trung',
      familyLineage: {
        father: 'Trần Thừa (Trần Thái Tổ)',
        siblings: ['Trần Liễu (An Sinh Vương)', 'Trần Nhật Hiệu', 'Trần Bà Liệt'],
        children: ['Trần Hoảng (Trần Thánh Tông)', 'Trần Quang Khải'],
      },
    },
  },
  'person_tran_thanh_tong': {
    entityId: 'person_tran_thanh_tong',
    canonicalName: 'Trần Thánh Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trần Hoảng', 'Vua Trần Thánh Tông'],
    timeRange: { start: 1240, end: 1290 },
    dynasty: 'Nhà Trần',
  },
  'person_tran_phu': {
    entityId: 'person_tran_phu',
    canonicalName: 'Trần Phú',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đồng chí Trần Phú', 'Tổng Bí thư Trần Phú', 'Tổng bí thư đầu tiên Trần Phú'],
    timeRange: { start: 1904, end: 1931 },
    dynasty: 'Thời kỳ Hiện đại',
    namingMetadata: {
      archetype: 'MODERN_FIGURE',
      birthName: 'Trần Phú',
      courtesyOrCommonName: 'Trần Phú',
      periodAliases: [
        { period: '1930 - 1931 (Tổng Bí thư đầu tiên của Đảng)', name: 'Trần Phú' },
      ],
    },
  },
  'person_phan_boi_chau': {
    entityId: 'person_phan_boi_chau',
    canonicalName: 'Phan Bội Châu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sào Nam', 'Cụ Phan Bội Châu'],
    timeRange: { start: 1867, end: 1940 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_phan_chau_trinh': {
    entityId: 'person_phan_chau_trinh',
    canonicalName: 'Phan Châu Trinh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tây Hồ', 'Cụ Phan Châu Trinh'],
    timeRange: { start: 1872, end: 1926 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_hoang_hoa_tham': {
    entityId: 'person_hoang_hoa_tham',
    canonicalName: 'Hoàng Hoa Thám',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đề Thám', 'Hùm xám Yên Thế'],
    timeRange: { start: 1858, end: 1913 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_le_thanh_tong': {
    entityId: 'person_le_thanh_tong',
    canonicalName: 'Lê Thánh Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Tư Thành', 'Vua Lê Thánh Tông'],
    timeRange: { start: 1442, end: 1497 },
    dynasty: 'Nhà Hậu Lê',
  },
  'person_chu_van_an': {
    entityId: 'person_chu_van_an',
    canonicalName: 'Chu Văn An',
    type: 'HISTORICAL_PERSON',
    aliases: ['Vạn Thế Sư Biểu', 'Tiều Ẩn'],
    timeRange: { start: 1292, end: 1370 },
    dynasty: 'Nhà Trần',
  },
  'person_trieu_quang_phuc': {
    entityId: 'person_trieu_quang_phuc',
    canonicalName: 'Triệu Quang Phục',
    type: 'HISTORICAL_PERSON',
    aliases: ['Dạ Trạch Vương', 'Triệu Việt Vương', 'Vua Triệu Việt Vương'],
    timeRange: { start: 548, end: 571 },
    dynasty: 'Vạn Xuân',
  },
  'person_khuc_thua_du': {
    entityId: 'person_khuc_thua_du',
    canonicalName: 'Khúc Thừa Dụ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Khúc Tiên Chủ', 'Tiết độ sứ Khúc Thừa Dụ'],
    timeRange: { start: 830, end: 907 },
    dynasty: 'Thời kỳ Tự chủ',
  },
  'person_van_tien_dung': {
    entityId: 'person_van_tien_dung',
    canonicalName: 'Văn Tiến Dũng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đại tướng Văn Tiến Dũng'],
    timeRange: { start: 1917, end: 2002 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_tran_quoc_toan': {
    entityId: 'person_tran_quoc_toan',
    canonicalName: 'Trần Quốc Toản',
    type: 'HISTORICAL_PERSON',
    aliases: ['Hoài Văn Hầu', 'Hoài Văn Hầu Trần Quốc Toản'],
    timeRange: { start: 1267, end: 1285 },
    dynasty: 'Nhà Trần',
  },
  'person_ly_thanh_tong': {
    entityId: 'person_ly_thanh_tong',
    canonicalName: 'Lý Thánh Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Nhật Tôn', 'Vua Lý Thánh Tông'],
    timeRange: { start: 1023, end: 1072 },
    dynasty: 'Nhà Lý',
  },
  'person_le_trang_tong': {
    entityId: 'person_le_trang_tong',
    canonicalName: 'Lê Trang Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Duy Ninh', 'Chúa Chổm', 'Vua Lê Trang Tông'],
    timeRange: { start: 1515, end: 1548 },
    dynasty: 'Lê Trung Hưng',
  },
  'person_nguyen_lu': {
    entityId: 'person_nguyen_lu',
    canonicalName: 'Nguyễn Lữ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đông Định Vương'],
    timeRange: { start: 1754, end: 1787 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_vuong_thong': {
    entityId: 'person_vuong_thong',
    canonicalName: 'Vương Thông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tổng binh Vương Thông'],
    timeRange: { start: 1390, end: 1452 },
    dynasty: 'Nhà Minh',
  },
  'person_nguyen_tri_phuong': {
    entityId: 'person_nguyen_tri_phuong',
    canonicalName: 'Nguyễn Tri Phương',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1800, end: 1873 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_truong_dinh': {
    entityId: 'person_truong_dinh',
    canonicalName: 'Trương Định',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bình Tây Đại Nguyên Soái', 'Trương Công Định'],
    timeRange: { start: 1820, end: 1864 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_ton_that_thuyet': {
    entityId: 'person_ton_that_thuyet',
    canonicalName: 'Tôn Thất Thuyết',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1839, end: 1913 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_nguyen_thi_dinh': {
    entityId: 'person_nguyen_thi_dinh',
    canonicalName: 'Nguyễn Thị Định',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nữ tướng Nguyễn Thị Định', 'Cô Ba Định'],
    timeRange: { start: 1920, end: 1992 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_nguyen_binh_khiem': {
    entityId: 'person_nguyen_binh_khiem',
    canonicalName: 'Nguyễn Bỉnh Khiêm',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trạng Trình', 'Trạng Trình Nguyễn Bỉnh Khiêm'],
    timeRange: { start: 1491, end: 1585 },
    dynasty: 'Nhà Mạc',
  },
  'person_nguyen_thai_hoc': {
    entityId: 'person_nguyen_thai_hoc',
    canonicalName: 'Nguyễn Thái Học',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1902, end: 1930 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_trinh_kiem': {
    entityId: 'person_trinh_kiem',
    canonicalName: 'Trịnh Kiểm',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thế Tổ Minh Khang Thái Vương'],
    timeRange: { start: 1503, end: 1570 },
    dynasty: 'Chúa Trịnh',
  },
  'person_bui_thi_xuan': {
    entityId: 'person_bui_thi_xuan',
    canonicalName: 'Bùi Thị Xuân',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nữ tướng Bùi Thị Xuân', 'Đô đốc Bùi Thị Xuân'],
    timeRange: { start: 1752, end: 1802 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_ham_nghi': {
    entityId: 'person_ham_nghi',
    canonicalName: 'Hàm Nghi',
    type: 'HISTORICAL_PERSON',
    aliases: ['Vua Hàm Nghi', 'Ưng Lịch'],
    timeRange: { start: 1871, end: 1944 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_khuc_hao': {
    entityId: 'person_khuc_hao',
    canonicalName: 'Khúc Hạo',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 860, end: 917 },
    dynasty: 'Thời kỳ Tự chủ',
  },
  'person_y_lan': {
    entityId: 'person_y_lan',
    canonicalName: 'Ỷ Lan',
    type: 'HISTORICAL_PERSON',
    aliases: ['Linh Nhân Hoàng thái hậu', 'Hoàng thái hậu Ỷ Lan'],
    timeRange: { start: 1044, end: 1117 },
    dynasty: 'Nhà Lý',
  },
  'person_than_nhan_trung': {
    entityId: 'person_than_nhan_trung',
    canonicalName: 'Thân Nhân Trung',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1419, end: 1499 },
    dynasty: 'Nhà Lê Sơ',
  },
  'person_ngo_thi_nham': {
    entityId: 'person_ngo_thi_nham',
    canonicalName: 'Ngô Thì Nhậm',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1746, end: 1803 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_ngo_van_so': {
    entityId: 'person_ngo_van_so',
    canonicalName: 'Ngô Văn Sở',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đại tư mã Ngô Văn Sở'],
    timeRange: { start: 1750, end: 1795 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_nguyen_trung_truc': {
    entityId: 'person_nguyen_trung_truc',
    canonicalName: 'Nguyễn Trung Trực',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1838, end: 1868 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_dinh_cong_trang': {
    entityId: 'person_dinh_cong_trang',
    canonicalName: 'Đinh Công Tráng',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1842, end: 1887 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_phan_dinh_phung': {
    entityId: 'person_phan_dinh_phung',
    canonicalName: 'Phan Đình Phùng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Cụ Phan Đình Phùng', 'Đình nguyên Phan Đình Phùng'],
    timeRange: { start: 1847, end: 1896 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_luong_van_can': {
    entityId: 'person_luong_van_can',
    canonicalName: 'Lương Văn Can',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1854, end: 1927 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_vo_van_kiet': {
    entityId: 'person_vo_van_kiet',
    canonicalName: 'Võ Văn Kiệt',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sáu Dân', 'Thủ tướng Võ Văn Kiệt'],
    timeRange: { start: 1922, end: 2008 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_duong_dinh_nghe': {
    entityId: 'person_duong_dinh_nghe',
    canonicalName: 'Dương Đình Nghệ',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 874, end: 937 },
    dynasty: 'Thời kỳ Tự chủ',
  },
  'person_le_lai': {
    entityId: 'person_le_lai',
    canonicalName: 'Lê Lai',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lê Lai cứu chúa'],
    timeRange: { start: 1390, end: 1419 },
    dynasty: 'Nhà Hậu Lê / Lam Sơn',
  },
  'person_ngo_si_lien': {
    entityId: 'person_ngo_si_lien',
    canonicalName: 'Ngô Sĩ Liên',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sử thần Ngô Sĩ Liên'],
    timeRange: { start: 1400, end: 1498 },
    dynasty: 'Nhà Hậu Lê',
  },
  'person_phung_hung': {
    entityId: 'person_phung_hung',
    canonicalName: 'Phùng Hưng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bố Cái Đại Vương', 'Bố Cái Đại Vương Phùng Hưng'],
    timeRange: { start: 761, end: 802 },
    dynasty: 'Thời kỳ Bắc thuộc',
    namingMetadata: {
      adversaries: ['Cao Chính Bình', 'Chính Bình'],
      familyLineage: {
        siblings: ['Phùng Hải', 'Phùng Dĩnh'],
        children: ['Phùng An'],
      },
    },
  },
  'person_mac_dinh_chi': {
    entityId: 'person_mac_dinh_chi',
    canonicalName: 'Mạc Đĩnh Chi',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lưỡng quốc Trạng nguyên', 'Lưỡng quốc Trạng nguyên Mạc Đĩnh Chi'],
    timeRange: { start: 1272, end: 1346 },
    dynasty: 'Nhà Trần',
  },
  'person_le_quy_don': {
    entityId: 'person_le_quy_don',
    canonicalName: 'Lê Quý Đôn',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bảng nhãn Lê Quý Đôn', 'Quế Đường'],
    timeRange: { start: 1726, end: 1784 },
    dynasty: 'Nhà Hậu Lê / Thời Lê-Trịnh',
  },
  'person_phung_khac_khoan': {
    entityId: 'person_phung_khac_khoan',
    canonicalName: 'Phùng Khắc Khoan',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trạng Bùng', 'Trạng Bùng Phùng Khắc Khoan'],
    timeRange: { start: 1528, end: 1613 },
    dynasty: 'Nhà Hậu Lê / Thời Lê Trung Hưng',
  },
  'person_nguyen_thiep': {
    entityId: 'person_nguyen_thiep',
    canonicalName: 'Nguyễn Thiếp',
    type: 'HISTORICAL_PERSON',
    aliases: ['La Sơn Phu Tử', 'La Sơn phu tử Nguyễn Thiếp'],
    timeRange: { start: 1723, end: 1804 },
    dynasty: 'Nhà Tây Sơn / Triều Lê Trung Hưng',
  },
  'person_le_van_huu': {
    entityId: 'person_le_van_huu',
    canonicalName: 'Lê Văn Hưu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sử gia Lê Văn Hưu'],
    timeRange: { start: 1230, end: 1322 },
    dynasty: 'Nhà Trần',
  },
  'person_phan_phu_tien': {
    entityId: 'person_phan_phu_tien',
    canonicalName: 'Phan Phu Tiên',
    type: 'HISTORICAL_PERSON',
    aliases: ['Sử gia Phan Phu Tiên'],
    timeRange: { start: 1370, end: 1460 },
    dynasty: 'Nhà Hậu Lê',
  },
  'person_phap_loa': {
    entityId: 'person_phap_loa',
    canonicalName: 'Pháp Loa',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thiền sư Pháp Loa', 'Đồng Kiên Cương'],
    timeRange: { start: 1284, end: 1330 },
    dynasty: 'Nhà Trần',
  },
  'person_huyen_quang': {
    entityId: 'person_huyen_quang',
    canonicalName: 'Huyền Quang',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thiền sư Huyền Quang', 'Lý Đạo Tái'],
    timeRange: { start: 1254, end: 1334 },
    dynasty: 'Nhà Trần',
  },
  'person_to_dinh': {
    entityId: 'person_to_dinh',
    canonicalName: 'Tô Định',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thái thú Tô Định'],
    timeRange: { start: 0, end: 50 },
    dynasty: 'Thời kỳ Bắc thuộc',
  },
  'person_che_cu': {
    entityId: 'person_che_cu',
    canonicalName: 'Chế Củ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Rudravarman III'],
    timeRange: { start: 1040, end: 1075 },
    dynasty: 'Vương quốc Chăm-pa',
  },
  'person_tran_anh_tong': {
    entityId: 'person_tran_anh_tong',
    canonicalName: 'Trần Anh Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trần Thuyên'],
    timeRange: { start: 1276, end: 1320 },
    dynasty: 'Nhà Trần',
  },
  'person_tran_quang_khai': {
    entityId: 'person_tran_quang_khai',
    canonicalName: 'Trần Quang Khải',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chiêu Minh Đại Vương', 'Chiêu Minh Đại Vương Trần Quang Khải'],
    timeRange: { start: 1241, end: 1294 },
    dynasty: 'Nhà Trần',
  },
  'person_tran_nhat_duat': {
    entityId: 'person_tran_nhat_duat',
    canonicalName: 'Trần Nhật Duật',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chiêu Văn Vương', 'Chiêu Văn Vương Trần Nhật Duật'],
    timeRange: { start: 1255, end: 1330 },
    dynasty: 'Nhà Trần',
  },
  'person_tran_quang_dieu': {
    entityId: 'person_tran_quang_dieu',
    canonicalName: 'Trần Quang Diệu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đô đốc Trần Quang Diệu'],
    timeRange: { start: 1760, end: 1802 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_nguyen_thi_binh': {
    entityId: 'person_nguyen_thi_binh',
    canonicalName: 'Nguyễn Thị Bình',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bà Nguyễn Thị Bình'],
    timeRange: { start: 1927, end: 2026 },
    dynasty: 'Việt Nam Dân chủ Cộng hòa',
  },
  'person_nguyen_van_linh': {
    entityId: 'person_nguyen_van_linh',
    canonicalName: 'Nguyễn Văn Linh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tổng Bí thư Nguyễn Văn Linh'],
    timeRange: { start: 1915, end: 1998 },
    dynasty: 'Cộng hòa Xã hội Chủ nghĩa Việt Nam',
  },
  'person_de_castries': {
    entityId: 'person_de_castries',
    canonicalName: 'Christian de Castries',
    type: 'HISTORICAL_PERSON',
    aliases: ['De Castries', 'tướng De Castries', 'Đờ Cát', 'tướng Đờ Cát'],
    timeRange: { start: 1902, end: 1991 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_cao_thang': {
    entityId: 'person_cao_thang',
    canonicalName: 'Cao Thắng',
    type: 'HISTORICAL_PERSON',
    aliases: [],
    timeRange: { start: 1864, end: 1893 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_ly_thai_tong': {
    entityId: 'person_ly_thai_tong',
    canonicalName: 'Lý Thái Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Phật Mã', 'Vua Lý Thái Tông', 'Thái tử Lý Phật Mã', 'Phật Mã'],
    timeRange: { start: 1000, end: 1054 },
    dynasty: 'Nhà Lý',
  },
  'person_ly_nhan_tong': {
    entityId: 'person_ly_nhan_tong',
    canonicalName: 'Lý Nhân Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Càn Đức', 'Vua Lý Nhân Tông'],
    timeRange: { start: 1066, end: 1127 },
    dynasty: 'Nhà Lý',
  },
  'person_ly_hue_tong': {
    entityId: 'person_ly_hue_tong',
    canonicalName: 'Lý Huệ Tông',
    type: 'HISTORICAL_PERSON',
    aliases: ['Lý Sảm', 'Vua Lý Huệ Tông', 'Huệ Tông'],
    timeRange: { start: 1194, end: 1226 },
    dynasty: 'Nhà Lý',
    namingMetadata: {
      birthName: 'Lý Sảm',
      templeName: 'Lý Huệ Tông',
      reignPeriod: { start: 1211, end: 1224 },
    },
  },
  'person_van_hanh': {
    entityId: 'person_van_hanh',
    canonicalName: 'Vạn Hạnh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thiền sư Vạn Hạnh', 'Quốc sư Vạn Hạnh', 'Sư Vạn Hạnh'],
    timeRange: { start: 938, end: 1018 },
    dynasty: 'Nhà Lý',
  },
  'person_dinh_lien': {
    entityId: 'person_dinh_lien',
    canonicalName: 'Đinh Liễn',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nam Việt Vương', 'Nam Việt Vương Đinh Liễn', 'Đinh Khuông Liễn'],
    timeRange: { start: 940, end: 979 },
    dynasty: 'Nhà Đinh',
  },
  'person_ho_han_thuong': {
    entityId: 'person_ho_han_thuong',
    canonicalName: 'Hồ Hán Thương',
    type: 'HISTORICAL_PERSON',
    aliases: ['Vua Hồ Hán Thương', 'Hán Thương'],
    timeRange: { start: 1400, end: 1407 },
    dynasty: 'Nhà Hồ',
  },
  'person_nguyen_phuc_nguyen': {
    entityId: 'person_nguyen_phuc_nguyen',
    canonicalName: 'Nguyễn Phúc Nguyên',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chúa Sãi', 'chúa Sãi', 'Chúa Nguyễn Phúc Nguyên', 'Định Quốc Công'],
    timeRange: { start: 1563, end: 1635 },
    dynasty: 'Chúa Nguyễn',
  },
  'person_nguyen_quang_toan': {
    entityId: 'person_nguyen_quang_toan',
    canonicalName: 'Nguyễn Quang Toản',
    type: 'HISTORICAL_PERSON',
    aliases: ['Cảnh Thịnh', 'Vua Cảnh Thịnh', 'Cảnh Thịnh Hoàng Đế'],
    timeRange: { start: 1783, end: 1802 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_nguyen_huu_canh': {
    entityId: 'person_nguyen_huu_canh',
    canonicalName: 'Nguyễn Hữu Cảnh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Thành Hầu Nguyễn Hữu Cảnh', 'Lễ Thành Hầu Nguyễn Hữu Cảnh', 'Lễ Thành Hầu', 'Chưởng cơ Nguyễn Hữu Cảnh'],
    timeRange: { start: 1650, end: 1700 },
    dynasty: 'Chúa Nguyễn',
  },
  'person_ho_xuan_huong': {
    entityId: 'person_ho_xuan_huong',
    canonicalName: 'Hồ Xuân Hương',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bà Chúa Thơ Nôm', 'Xuân Hương'],
    timeRange: { start: 1772, end: 1822 },
    dynasty: 'Nhà Tây Sơn',
  },
  'person_nguyen_dinh_chieu': {
    entityId: 'person_nguyen_dinh_chieu',
    canonicalName: 'Nguyễn Đình Chiểu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Cụ Đồ Chiểu', 'Đồ Chiểu'],
    timeRange: { start: 1822, end: 1888 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_vo_thi_sau': {
    entityId: 'person_vo_thi_sau',
    canonicalName: 'Võ Thị Sáu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chị Sáu', 'Nữ anh hùng Võ Thị Sáu'],
    timeRange: { start: 1933, end: 1952 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_nguyen_thi_ut': {
    entityId: 'person_nguyen_thi_ut',
    canonicalName: 'Nguyễn Thị Út',
    type: 'HISTORICAL_PERSON',
    aliases: ['Chị Út Tịch', 'Út Tịch'],
    timeRange: { start: 1931, end: 1968 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_ton_duc_thang': {
    entityId: 'person_ton_duc_thang',
    canonicalName: 'Tôn Đức Thắng',
    type: 'HISTORICAL_PERSON',
    aliases: ['Bác Tôn', 'Chủ tịch Tôn Đức Thắng'],
    timeRange: { start: 1888, end: 1980 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_nguyen_thi_suot': {
    entityId: 'person_nguyen_thi_suot',
    canonicalName: 'Nguyễn Thị Suốt',
    type: 'HISTORICAL_PERSON',
    aliases: ['Mẹ Suốt'],
    timeRange: { start: 1906, end: 1968 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_nguyen_thi_thu': {
    entityId: 'person_nguyen_thi_thu',
    canonicalName: 'Nguyễn Thị Thứ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Mẹ Thứ', 'Mẹ Việt Nam anh hùng Nguyễn Thị Thứ'],
    timeRange: { start: 1904, end: 2010 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_nguyen_van_thanh': {
    entityId: 'person_nguyen_van_thanh',
    canonicalName: 'Nguyễn Văn Thành',
    type: 'HISTORICAL_PERSON',
    aliases: ['Tổng trấn Nguyễn Văn Thành', 'Tổng trấn Bắc Thành Nguyễn Văn Thành', 'Tổng trấn Bắc Thành'],
    timeRange: { start: 1758, end: 1817 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_truong_chinh': {
    entityId: 'person_truong_chinh',
    canonicalName: 'Trường Chinh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Đặng Xuân Khu', 'Tổng Bí thư Trường Chinh', 'Anh Năm'],
    timeRange: { start: 1907, end: 1988 },
    dynasty: 'Thời kỳ Hiện đại',
  },
  'person_phan_khoi': {
    entityId: 'person_phan_khoi',
    canonicalName: 'Phan Khôi',
    type: 'HISTORICAL_PERSON',
    aliases: ['nhà báo Phan Khôi'],
    timeRange: { start: 1887, end: 1959 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_the_lu': {
    entityId: 'person_the_lu',
    canonicalName: 'Thế Lữ',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Thứ Lễ', 'nhà thơ Thế Lữ'],
    timeRange: { start: 1907, end: 1989 },
    dynasty: 'Thời kỳ Pháp thuộc / Hiện đại',
  },
  'person_hoai_thanh': {
    entityId: 'person_hoai_thanh',
    canonicalName: 'Hoài Thanh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Đức Nguyên', 'nhà phê bình Hoài Thanh'],
    timeRange: { start: 1909, end: 1982 },
    dynasty: 'Thời kỳ Pháp thuộc / Hiện đại',
  },
  'person_pham_huu_nhat': {
    entityId: 'person_pham_huu_nhat',
    canonicalName: 'Phạm Hữu Nhật',
    type: 'HISTORICAL_PERSON',
    aliases: ['Suất đội Phạm Hữu Nhật', 'Thủy quân Suất đội Phạm Hữu Nhật'],
    timeRange: { start: 1804, end: 1854 },
    dynasty: 'Nhà Nguyễn',
  },
  'person_le_van_thinh': {
    entityId: 'person_le_van_thinh',
    canonicalName: 'Lê Văn Thịnh',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trạng nguyên Lê Văn Thịnh', 'Thái sư Lê Văn Thịnh'],
    timeRange: { start: 1050, end: 1096 },
    dynasty: 'Nhà Lý',
  },
  'person_nguyen_hien': {
    entityId: 'person_nguyen_hien',
    canonicalName: 'Nguyễn Hiền',
    type: 'HISTORICAL_PERSON',
    aliases: ['Trạng nguyên Nguyễn Hiền', 'Trạng nguyên trẻ tuổi nhất'],
    timeRange: { start: 1234, end: 1256 },
    dynasty: 'Nhà Trần',
  },
  'person_xuan_dieu': {
    entityId: 'person_xuan_dieu',
    canonicalName: 'Xuân Diệu',
    type: 'HISTORICAL_PERSON',
    aliases: ['Ngô Xuân Diệu', 'nhà thơ Xuân Diệu'],
    timeRange: { start: 1916, end: 1985 },
    dynasty: 'Thời kỳ Pháp thuộc / Hiện đại',
  },
  'person_huy_can': {
    entityId: 'person_huy_can',
    canonicalName: 'Huy Cận',
    type: 'HISTORICAL_PERSON',
    aliases: ['Cù Huy Cận', 'nhà thơ Huy Cận'],
    timeRange: { start: 1919, end: 2005 },
    dynasty: 'Thời kỳ Pháp thuộc / Hiện đại',
  },
  'person_han_mac_tu': {
    entityId: 'person_han_mac_tu',
    canonicalName: 'Hàn Mặc Tử',
    type: 'HISTORICAL_PERSON',
    aliases: ['Nguyễn Trọng Trí', 'Hàn Mạc Tử'],
    timeRange: { start: 1912, end: 1940 },
    dynasty: 'Thời kỳ Pháp thuộc',
  },
  'person_che_lan_vien': {
    entityId: 'person_che_lan_vien',
    canonicalName: 'Chế Lan Viên',
    type: 'HISTORICAL_PERSON',
    aliases: ['Phan Ngọc Hoan', 'nhà thơ Chế Lan Viên'],
    timeRange: { start: 1920, end: 1989 },
    dynasty: 'Thời kỳ Pháp thuộc / Hiện đại',
  },
};
